openapi: 3.0.3 
info:
  title: Procurment Workflow
  version: 1.0.0
  description: Procurment Workflow API specification
servers:
  - url: '{protocol}://{ip}:{port}/{base-api}'
    variables:
      protocol:
        enum:
          - http
          - https
        default: http
      ip:
        enum:
          - localhost
          - 34.199.12.114
        default: localhost
      port:
        enum:
          - '9000'
        default: '9000'
      base-api:
        enum:
          - api
        default: api

tags:
  - name: Project
    description: perform CRUD operations on project table

paths:
  /getProject:
    get:
      tags:
        - Project
      summary: Fetch list of project
      operationId: getAllProject
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProjectDTO'
        404:
          description: "Service Not found"
        500:
          description: "Internal Server Error"
  /addProject:
    post:
      tags:
        - Project
      summary: Add project
      operationId: addProject
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProjectDTO'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectDTO'
        404:
          description: "Service Not found"
        500:
          description: "Internal Server Error"
   
  /updateProject/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: integer
          format: int64
        required: true
    put:
      tags:
        - Project
      summary: Fetch an project an update of given id
      operationId: updateProject
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProjectDTO'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectDTO'
        404:
          description: "Service Not found"
        500:
          description: "Internal Server Error"
          
  /deleteProject/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: integer
          format: int64
        required: true
    delete:
      tags:
        - Project
      summary: Fetch an project an delete of given id
      operationId: deleteProject
      responses:
        200:
          description: "Project deleted successfully"
        404:
          description: "Service Not found"
        500:
          description: "Internal Server Error"
components:
  schemas:
    ProjectDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        manager:
          type: string
        description:
          type: string
        resources:
          type: string
        department:
          type: string
        startDate:
          type: string
          format: date  
        endDate:
          type: string
          format: date  
        status:
          type: string
        createdBy:
          type: string
        updatedBy:
          type: string
        createdOn:
          type: string
          format: date-time 
        updatedOn:
          type: string
          format: date-time  

       
    